### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by devkhan** [SBRG/EscherConverter#3]
This is a tracker issue for the tasks which are at current priority before starting to actually implement the conversion. Refer [this](https://github.com/devkhan/EscherConverter/wiki/IDEAS).

To-Do:

Higher Priority:

- [x] Refactor #7 
- [x] Code cleanup #7 
- [x] Unit tests (In progress, always will be) #1 
- [x] Continous Integration (Travis, CircleCI, etc.) c80124f47a4139ea6ca08cfd55cd48575216e6bc

Near future:

- [x] JSON-Schema validator
- [ ] ~~Generic classes (not sure right now)~~
- [x] Migrate JSON library (maybe) #11 

Main tasks:

- [x] SBGN -> Escher conversion #12 (partially working)
- [x] SBML -> Escher conversion #13 (partially working)
- [x] Schematron validation (See #5)

Later half:

- [x] Web app
- [x] Front-end

NOTE: All of these topics will be discussed in their own issue/PR, this is just a tracker for their progress.

Will keep adding as we go.
Please make changes as you think are necessary.

/cc @zakandrewking @draeger
